package Menu;

import Conversor.Conversor;
import Registro.Registro;
import Saludar.Saludar;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author relznd
 */
public class Opciones extends javax.swing.JFrame {

    /**
     * Creates new form Opciones
     */
    public Opciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mitSaludar = new javax.swing.JMenuItem();
        mitConvertir = new javax.swing.JMenuItem();
        mitRegistro = new javax.swing.JMenuItem();
        mitSalir = new javax.swing.JMenuItem();

        jLabel1.setIcon(new javax.swing.ImageIcon("/home/relznd/Pictures/Universidad/img/backgorund.gif")); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu de Opciones");

        jLabel2.setIcon(new javax.swing.ImageIcon("/home/relznd/Pictures/Universidad/img/backgorund.gif")); // NOI18N

        jMenuBar1.setBackground(new java.awt.Color(0, 0, 0));

        jMenu1.setForeground(new java.awt.Color(255, 255, 255));
        jMenu1.setText("Opciones");
        jMenu1.setPreferredSize(new java.awt.Dimension(80, 40));

        mitSaludar.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        mitSaludar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/robot.png"))); // NOI18N
        mitSaludar.setText("Saludar");
        mitSaludar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitSaludarActionPerformed(evt);
            }
        });
        jMenu1.add(mitSaludar);

        mitConvertir.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        mitConvertir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/robot.png"))); // NOI18N
        mitConvertir.setText("Convertir");
        mitConvertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitConvertirActionPerformed(evt);
            }
        });
        jMenu1.add(mitConvertir);

        mitRegistro.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        mitRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/robot.png"))); // NOI18N
        mitRegistro.setText("Registro");
        mitRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitRegistroActionPerformed(evt);
            }
        });
        jMenu1.add(mitRegistro);

        mitSalir.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        mitSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/robot.png"))); // NOI18N
        mitSalir.setText("Salir");
        jMenu1.add(mitSalir);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mitSaludarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitSaludarActionPerformed
        // TODO add your handling code here:
        Saludar sal = new Saludar();
        sal.setVisible(true);
        sal.setLocationRelativeTo(null);
    }//GEN-LAST:event_mitSaludarActionPerformed

    private void mitConvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitConvertirActionPerformed
        // TODO add your handling code here:
        Conversor c = new Conversor();
        c.setVisible(true);
        c.setLocationRelativeTo(null);
    }//GEN-LAST:event_mitConvertirActionPerformed

    private void mitRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitRegistroActionPerformed
        // TODO add your handling code here:
        Registro r = new Registro();
        r.setVisible(true);
        r.setLocationRelativeTo(null);
    }//GEN-LAST:event_mitRegistroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Opciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Opciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Opciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Opciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Opciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mitConvertir;
    private javax.swing.JMenuItem mitRegistro;
    private javax.swing.JMenuItem mitSalir;
    private javax.swing.JMenuItem mitSaludar;
    // End of variables declaration//GEN-END:variables
}
